version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: week-planner-app
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_PATH: /app/data/app.db
      SESSION_TTL_HOURS: 12
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    
      CORS_ORIGIN: https://docente.rootgamez.dev,https://rootgamez.dev
    volumes:
      - app_data:/app/data
    
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true

volumes:
  app_data: